### ISSUE TITLE
BUG: Wrong indentation in generated deployment.yaml

### ISSUE THREAD

**Issue by PatrickE94** [restatedev/restate-operator#14]
Hi!

I'm keen on trying out this operator. I've been watching restate for a while and the addition of scalable deployments was the last thing required for me to give it a run!

However, I tried adding my tracing endpoints to the operator, but the generated YAML became invalid

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: restate-operator
    app.kubernetes.io/instance: restate
    app.kubernetes.io/name: restate-operator
    app.kubernetes.io/version: 1.2.0
  name: restate-operator
  namespace: restate-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restate-operator
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: restate-operator
        signoz.io/port: '8080'
        signoz.io/scrape: 'true'
      labels:
        app: restate-operator
    spec:
      containers:
        - env:
            - name: RUST_LOG
              value: info,restate=debug
          image: ghcr.io/restatedev/restate-operator:1.2.0
          imagePullPolicy: IfNotPresent
          name: restate-operator
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 3000
            runAsNonRoot: true
            runAsUser: 1000
        - name: OPENTELEMETRY_ENDPOINT_URL
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          value: http://signoz-otel-collector.signoz.svc.cluster.local:4317
      securityContext:
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch
      serviceAccountName: restate-operator
```

Note the indentiation for `- name: OPENT...` and `value: http://signoz...`. They're being evaluated as container name instead. I'm guessing this is just modifying [this line](https://github.com/restatedev/restate-operator/blob/main/charts/restate-operator-helm/templates/deployment.yaml#L50) to 12 instead of 8. 

For now, I'm continuing without tracing.

Good efforts!

// Patrick
